apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-page-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - pactnote.com # THE MAIN DOMAIN
    secretName: main-site-tls # Separate TLS secret for the main domain
  rules:
  - host: pactnote.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landing-page-service # Connect to the new service
            port:
              number: 80
